theme: jekyll-theme-minimal
title: Watch better movies!
name: BetterWatch
description: BetterWatch is a mobile app which lets you match movies with your friends and family so you can find movies/TV shows to watch together.
