#page title
page_title                                : BetterWatch                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://betterwatch.app/apple                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : app-armeabi-v7a-release.apk # https://play.google.com/store/apps/dev?id=7495307227988046122                                          # Enter Google Play Store URL.
presskit_download_link                    : # https://whateverhappns.github.io                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : BetterWatch                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free · In App Purchases                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Personalized, AI-Powered Recommendations

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Tammo Tesmer                                
your_link                                 : # https://whateverhappns.github.io                     
your_city                                 :                                 
email_address                             : ttesmer.dev@gmail.com
facebook_username                         : # ttesmer                                        
instagram_username                        : # ttesmer
twitter_username                          : # ttesmer
github_username                           : # WhateverHappns
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Get Personalized Recommendations
    description                           : Our state-of-the-art AI recommendation system gives insanely accurate recommendations tailored to your liking.
    fontawesome_icon_name                 : magic
    
  - title                                 : Our Promise
    description                           : Reduce the time you spend mindlessly scrolling on netflix. We focus on novelty meaning you won't be seeing the same shows all the time.
    fontawesome_icon_name                 : film

  - title                                 : Matching
    description                           : Create sessions with your friends & family and build a list of matched movies. Don't waste your precious time together deciding what to watch.
    fontawesome_icon_name                 : user-friends
    
  - title                                 : Detailed Descriptions
    description                           : See detailed movie & TV show descriptions with actors, seasons, providers (e.g. Netflix), trailers, genres and more. 
    fontawesome_icon_name                 : info-circle

#  - title                                 : Automatic Icon and Metadata
#    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
#    fontawesome_icon_name                 : sync

#  - title                                 : Easy to Tweak
#    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : adjust
  
#  - title                                 : Feature List
#    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : star

#  - title                                 : Smart App Banner
#    description                           : Display a smart app banner on iOS devices.
#    fontawesome_icon_name                 : arrow-alt-circle-down

#  - title                                 : Social Links
#    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : link





# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

base_url: "/BetterWatch"

collections:
  pagesfooter:
    output: true
    permalink: /:path/
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
